language: node_js
node_js: 9
before_script:
  - npm install yarn webpack -g
  - cd crx
  - yarn
  - cd ..
  - yarn
script:
  - yarn build
  - cd crx
  - yarn build
cache:
  directories:
    - "node_modules"
    - "crx/node_modules"
  - yarn: true
  - webpack: true