language: node_js
node_js: 9
before_script:
  - npm install yarn webpack -g
  - cd crx
  - yarn
  - cd ..
  - yarn
script:
  - yarn build
  - cd crx
  - yarn build
after_success:
  - git commit -a -m "Travis build"
  - git push origin master
cache:
  yarn: true
  webpack: true
  directories:
    - "node_modules"
    - "crx/node_modules"